#!/usr/bin/env bash
# Installing nginx web server
sudo apt -y update
sudo apt -y install nginx
sudo sed -i '/listen 80 default_server;/c\listen 80;' /etc/nginx/nginx.conf
echo 'Hello World' > /var/www/html/index.html
service nginx start
