#!/usr/bin/env bash
# Redirection
sudo apt -y update
sudo apt -y install nginx
echo 'Hello World' > /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
