#!/usr/bin/env bash
# Redirection
sudo apt -y update
sudo apt -y install nginx
echo 'Hello World' > /var/www/html/index.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo service nginx restart
