#!/usr/bin/env bash
# Installing haproxy load balancer
sudo apt -y update
sudo apt -y install haproxy
sudo sed -i "s/^ENABLED=.*/ENABLED=1/g" /etc/default/haproxy
configHaproxy=\
"
frontend http_frontend
    bind *:80
    mode http
    default_backend web-backend
backend web-backend
    mode http
    balance roundrobin
    server 336860-web-01 54.237.88.98 check
    server 336860-web-02 35.153.67.97 check
"
echo "$configHaproxy" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
