#!/usr/bin/env bash
# Loops from 1 to 10
# Displays "bad luck" for 4th loop
# "good luck" for 8th loop
# "Best School" for the other iterations
i=1
while [ $i -lt 11 ]
do
  if [ $i == 4 ]
  then
    echo "bad luck"
  elif [ $i == 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
