#!/usr/bin/env bash
# Loops from 1 to 20
# Displays 4 & "bad luck from China" for 4th loop
# 9 & "bad luck from Japan" for 9th loop
# 17 & "bad luck from Italy" for 17th loop
i=1
while [ $i -lt 21 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
    esac
  ((i++))
done
