#!/usr/bin/env bash
# Installing ufw firewall and enabing SSH, HTTPS & HTTP
sudo apt -y update
sudo apt install ufw

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
sudo ufw status verbose
