#!/usr/bin/env bash
# Run as user nginx not root
pkill -9 apache2
sed -i 's/80/8080/g' etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sed -i 'ls/.*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
